spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: '/api/v1'
jwt:
  secret-key: "Xp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$"
  expiration-time: 36000000
springdoc:
  api-docs:
    enabled: true
